[package]
name = "jupiter-client-proto"
version = "0.1.0"
authors = ["Guillaume Ballet <gballet@gmail.com>"]
edition = "2018"

[dependencies]
rusqlite = "^0.21.0"
clap = "^2.33.0"
hex = "^0.3.1"
multiproof-rs = "^0.1.7"
jupiter-account = "^0.1.2"
rlp = "0.4.4"
